#!/usr/bin/env bash
# Downloads the GraphQL schema of a Stash release into
# lib/core/api/stash_schema.graphql, which graphql_codegen generates the
# API types from (1.8). Then regenerate:
#   tool/update_stash_schema.sh v0.31.1
#   dart run build_runner build --delete-conflicting-outputs
set -euo pipefail

version="${1:?usage: $0 <stash release tag, e.g. v0.31.1>}"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/lib/core/api/stash_schema.graphql"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl -fsSL "https://codeload.github.com/stashapp/stash/tar.gz/refs/tags/$version" \
  | tar xz -C "$tmp" --wildcards '*/graphql/schema/*'
schema_dir="$(echo "$tmp"/*/graphql/schema)"

{
  echo "# Stash $version GraphQL schema, from https://github.com/stashapp/stash/tree/$version/graphql/schema"
  echo "# Generated by tool/update_stash_schema.sh; don't edit."
  echo
  cat "$schema_dir/schema.graphql"
  find "$schema_dir/types" -name '*.graphql' | sort | while read -r file; do
    echo
    cat "$file"
  done
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines)"
